# Generated by Django 3.2.18 on 2023-08-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_ticket'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_event', to='events.Event', verbose_name='Избранное'),
        ),
    ]
