# Generated by Django 3.2.18 on 2023-08-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_id',
        ),
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(default=1, max_length=80, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
