# Generated by Django 3.2.18 on 2023-08-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_artist_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artisttype',
            options={'verbose_name': 'Тип артиста', 'verbose_name_plural': 'Типы артистов'},
        ),
    ]
