# Generated by Django 3.2.18 on 2023-08-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_artisttype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.IntegerField(default=0, verbose_name='Виртуальный счёт'),
        ),
    ]
