# Generated by Django 3.2.18 on 2023-08-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20230811_0121'),
        ('users', '0005_customuser_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='ArtistType',
        ),
    ]
