# Generated by Django 3.2.18 on 2023-08-15 20:32

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Название')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=events.models.Event.get_path, verbose_name='Баннер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('age_limit', models.IntegerField(blank=True, default=0, verbose_name='Возрастное орграничение')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Цена')),
                ('total_tickets', models.IntegerField(blank=True, default=0, verbose_name='Количество билетов')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('artist', models.CharField(blank=True, max_length=256, null=True, verbose_name='Артист')),
                ('pushkin_payment', models.BooleanField(default=False, verbose_name='Оплата по пушкинской')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=events.models.EventImage.get_path, verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Файл события',
                'verbose_name_plural': 'Файлы события',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Площадка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('location_data', models.JSONField(blank=True, null=True, verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(blank=True, default=False, verbose_name='Посетил')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets_event', to='events.event', verbose_name='Выступление')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
