# Generated by Django 3.2.18 on 2023-08-03 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='events_artist', to='users.Artist', verbose_name='Артисты'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='event',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='events_comment', to='events.Comment', verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='event',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.platform', verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='events.Tag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Авор'),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(to='events.Tag', verbose_name='Тэги'),
        ),
    ]
