# Generated by Django 3.2.20 on 2023-08-03 07:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_artist_artisttype'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Площадка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.TextField(verbose_name='Расположение')),
                ('support_phone', models.CharField(max_length=100, verbose_name='Телефон поддержки')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='events_artist', to='users.Artist', verbose_name='Артисты'),
        ),
        migrations.AddField(
            model_name='event',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Событие открыто'),
        ),
        migrations.AddField(
            model_name='event',
            name='persons_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество человек'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_limit',
            field=models.IntegerField(default=0, verbose_name='Возрастное орграничение'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
                ('user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Авор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='events_comment', to='events.Comment', verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='event',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.platform', verbose_name='Площадка'),
        ),
    ]
