# Generated by Django 3.2.18 on 2023-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pushkin_payment',
            field=models.BooleanField(default=False, verbose_name='Оплата по пушкинской'),
        ),
    ]
