# Generated by Django 3.2.18 on 2023-08-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='persons_limit',
        ),
        migrations.AddField(
            model_name='event',
            name='remain_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Билетов осталось'),
        ),
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего билетов'),
        ),
    ]
