# Generated by Django 3.2.18 on 2023-08-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_pushkin_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='ticket_types',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_sold',
            field=models.IntegerField(default=0, verbose_name='Билетов продано'),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_total',
            field=models.IntegerField(default=0, verbose_name='Количество билетов'),
        ),
        migrations.AddField(
            model_name='performance',
            name='tickets_sold',
            field=models.IntegerField(default=0, verbose_name='Билетов продано'),
        ),
        migrations.AddField(
            model_name='performance',
            name='tickets_total',
            field=models.IntegerField(default=0, verbose_name='Количество билетов'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets_event', to='events.event', verbose_name='Выступление'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
