# Generated by Django 3.2.18 on 2023-08-03 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_alter_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='remain_tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='events_user', to=settings.AUTH_USER_MODEL, verbose_name='Артисты'),
        ),
    ]
