# Generated by Django 3.2.18 on 2023-08-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20230816_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='adress',
            new_name='address',
        ),
    ]
