# Generated by Django 3.2.18 on 2023-08-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='when',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время'),
        ),
    ]
