# Generated by Django 3.2.18 on 2023-08-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_want_pushkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('events', models.ManyToManyField(blank=True, related_name='eventtopics_event', to='events.Event', verbose_name='События')),
            ],
            options={
                'verbose_name': 'Подборка событий',
                'verbose_name_plural': 'Подборки событий',
            },
        ),
    ]
