# Generated by Django 3.2.18 on 2023-08-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Артист'),
        ),
    ]
