# Generated by Django 3.2.18 on 2023-08-05 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='events/images/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Баннер'),
        ),
    ]
