# Generated by Django 3.2.18 on 2023-08-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='events/images/', verbose_name='Баннер'),
        ),
    ]
