# Generated by Django 3.2.18 on 2023-08-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_entrycondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.entrycondition', verbose_name='Условия входа'),
        ),
    ]
