# Generated by Django 3.2.18 on 2023-08-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Файл события',
                'verbose_name_plural': 'Файлы события',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='Баннер'),
        ),
    ]
