# Generated by Django 3.2.18 on 2023-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20230807_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='events_image', to='events.EventImage', verbose_name='Фотографии мероприятия'),
        ),
    ]
