# Generated by Django 3.2.18 on 2023-08-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20230808_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(default='Зал', max_length=255, verbose_name='Сектор')),
                ('tickets_number', models.IntegerField(default=0, verbose_name='Количество билетов')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Типы билетов',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='when',
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events_tag', to='events.Tag', verbose_name='Тэги'),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Выступление', max_length=255, verbose_name='Название выступления')),
                ('time', models.TimeField(verbose_name='Время')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('ticket_types', models.ManyToManyField(blank=True, related_name='performances_tickettype', to='events.TicketType', verbose_name='Типы билетов')),
            ],
            options={
                'verbose_name': 'Выступление',
                'verbose_name_plural': 'Выступления',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='performances',
            field=models.ManyToManyField(blank=True, related_name='events_performance', to='events.Performance', verbose_name='Выступления'),
        ),
    ]
