# Generated by Django 3.2.18 on 2023-08-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20230808_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name': 'Тип билета', 'verbose_name_plural': 'Типы билетов'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_tickets',
        ),
    ]
