# Generated by Django 3.2.18 on 2023-08-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20230808_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
