# Generated by Django 3.2.18 on 2023-08-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_performance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='tickets_sold',
            field=models.IntegerField(default=0, verbose_name='Билетов продано'),
        ),
    ]
