# Generated by Django 3.2.18 on 2023-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_tickettype_tickets_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='open',
            field=models.BooleanField(blank=True, default=True, verbose_name='Открыто'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='open',
            field=models.BooleanField(blank=True, default=True, verbose_name='Открыто'),
        ),
    ]
