# Generated by Django 3.2.18 on 2023-08-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20230809_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_number',
            field=models.IntegerField(default=0, verbose_name='Количество билетов'),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_sold',
            field=models.IntegerField(default=0, verbose_name='Билетов продано'),
        ),
    ]
