# Generated by Django 3.2.18 on 2023-08-10 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20230810_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='performance',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets_performance', to='events.performance', verbose_name='Выступление'),
            preserve_default=False,
        ),
    ]
