# Generated by Django 3.2.18 on 2023-08-15 08:22

from django.db import migrations, models
import routes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Маршрут')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=routes.models.Route.get_path, verbose_name='Баннер')),
                ('waypoints', models.JSONField(blank=True, null=True, verbose_name='Маршруты')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
    ]
