# Generated by Django 3.2.18 on 2023-08-15 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='routes_user', to=settings.AUTH_USER_MODEL, verbose_name='Билеты'),
        ),
    ]
