# Generated by Django 3.2.18 on 2023-08-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='routes/images/', verbose_name='Баннер'),
        ),
    ]
