# Generated by Django 3.2.18 on 2023-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_customroute_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Протяжённость'),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность'),
        ),
    ]
