# Generated by Django 3.2.18 on 2023-08-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='dat',
            field=models.JSONField(blank=True, null=True, verbose_name='Джсон'),
        ),
    ]
