# Generated by Django 3.2.18 on 2023-08-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_waypoint_dat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='waypoints',
        ),
        migrations.DeleteModel(
            name='Waypoint',
        ),
    ]
