# Generated by Django 3.2.18 on 2023-08-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20230805_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный отдых'),
        ),
    ]
