# Generated by Django 3.2.18 on 2023-08-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_route_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='routes/images/', verbose_name='Баннер'),
        ),
    ]
