# Generated by Django 3.2.18 on 2023-08-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_alter_route_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='age_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возрастное ограничение'),
        ),
    ]
