# Generated by Django 3.2.18 on 2023-08-10 21:55

from django.db import migrations, models
import routes.models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_route_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=routes.models.Route.get_path, verbose_name='Баннер'),
        ),
    ]
