# Generated by Django 3.2.18 on 2023-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_alter_route_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='routetype',
            name='query_text',
            field=models.TextField(default=1, verbose_name='Текст 2GIS запроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активный отдых'),
        ),
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена'),
        ),
    ]
